apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-frontend-pv
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-frontend-pvc
spec:
  storageClassName: example-frontend-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
